#!/usr/bin/python3
# ******************************************************************************
# Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
# licensed under the Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#     http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
# PURPOSE.
# See the Mulan PSL v2 for more details.
# ******************************************************************************/
try:
    from packageship_panel.application.core.task import Synchronization
    from packageship.libs.log import LOGGER

except ImportError as error:
    print("Import error,{msg}".format(msg=str(error)))
else:
    try:
        Synchronization().run()
    except (RuntimeError, KeyboardInterrupt, SystemExit) as error:
        LOGGER.error(error)
        print("The scheduled task has been stopped.")
